project_id = "gjaafbzhkdekgigmnafp"

[functions.verify-woocommerce-purchase]
verify_jwt = false

[functions.import-sacred-rewrite-cards]
verify_jwt = false

[functions.fix-placeholder-cards]
verify_jwt = false

[functions.healing-bot]
verify_jwt = false

[functions.areekeera-bot]
verify_jwt = false
